### ISSUE TITLE
Feedback from Yan Zeng

### ISSUE THREAD

**Issue by Owl64901** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#102]
Hi Team 19,

Great work! The Global Food Price Tracker Dashboard presents an essential tool for stakeholders looking to understand food pricing trends worldwide. The design choices, like the color coding for different markets, facilitate quick and straightforward interpretation of complex datasets. Below are several observations and suggestions:

#### Larger points
- [ ] The dashboard layout is intuitive. However, a brief tutorial for first-time users could improve new user experience. You might consider adding interactive elements, such as tooltips that explain what each plot represents, to make it more intuitive.
- [ ] The plots chosen are suitable for a quick glance at trends. Using a calendar to pick exact dates could be cumbersome for users who are looking for general trends rather than precise time points. I suggest implementing interactive sliders for time range selection. Sliders provide a quick and dynamic way to adjust the date range, giving users the ability to easily expand or narrow down the time period they are interested in without the need to input exact dates.
- [ ] I noticed that your proposal mentions the inclusion of a geographic view toggle. However, in the current dashboard, activating this toggle does not seem to initiate any change. Specifically, the geographical representation of data is not displayed, and only the line graph for the Food Price Index remains visible.
- [ ] When switching countries in the dashboard, I've noticed the plots take a while to update, possibly due to the large amount of data being processed. You might consider data sampling, such as displaying one data point per month. This can help in speeding up the plot updates without losing the overall trend information that users are interested in.

#### Smaller points
- [ ] Including a glossary or an info icon to explain technical terms like 'MoM' and 'YoY' could be beneficial for users unfamiliar with these terms. #120 
- [ ] Text is clear but might benefit from a slightly larger font size to aid readability on smaller screens.

**Comment by JohnShiuMK** [comment]
duplicated in #106, closed
