### ISSUE TITLE
Feedback from Iris LUO

### ISSUE THREAD

**Issue by iris0614** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#103]
### Introduction
I've had the opportunity to explore the Global Food Price Tracker Dashboard, and I am impressed with the design and functionality aimed at providing insights into global food pricing trends. Below, I offer my feedback structured into larger and smaller points for potential improvements.

#### User Interface and Experience
- **Intuitiveness:** The dashboard layout is intuitive; however, adding a brief tutorial could significantly enhance the user experience for newcomers. Interactive elements like tooltips would further aid in understanding the data plots.
- **Time Navigation:** While the use of a calendar for selecting dates is comprehensive, it may not be the most efficient for users seeking broader trends. Implementing a slider for time range selection could provide a more dynamic and straightforward way to adjust views between specific and general timelines.

#### Functionality Issues
- **Widget Interaction:** I noticed some issues with the interactive widgets. Specifically, selecting different options does not update the plots accordingly, which might be frustrating for users expecting real-time data manipulation.
- **Geographic View:** The inclusion of a geographic view toggle is a great idea, yet it seems non-functional at the moment. Activating this should display different geographical data visualizations to enhance the comparative analysis between regions or countries.

#### Performance Optimization
- **Data Loading Speed:** Transitioning between different countries or data points is somewhat slow. Optimizing data processing or considering data sampling (e.g., showing one data point per month) could improve responsiveness and user satisfaction.

#### Layout and Organization
- **Dashboard Layout:** The current layout is well-organized, yet considering the feedback from actual users on whether the rows/columns setup is optimal could provide insights into potential improvements.
- **Label Clarity:** Ensure that all plot labels, widget titles, and other text elements are clear and easy to read. Experimenting with different fonts or orientations could enhance visibility and user interaction.

### Additional Suggestions
- **Extension of Features:** Consider extending the dashboard functionalities to include more varied plot types beyond time series to cover other relevant aspects of food pricing data.
- **Readme and Documentation:** Ensure that the readme document is clear and comprehensive enough to understand the dashboard’s capabilities and how to navigate it effectively without prior in-depth knowledge.
- please check the message: 
<img width="1021" alt="19" src="https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker/assets/143670925/8ddb276a-a9c9-4f1a-a950-1c2a8e04536b">

### Conclusion
I hope these observations are helpful as you continue to refine this essential tool. The dashboard already stands as a valuable resource, and with these enhancements, it could become even more pivotal for stakeholders in the food industry.

**Comment by JohnShiuMK** [comment]
duplicated in #106, closed
