### ISSUE TITLE
Feedback from Orix Au Yeung

### ISSUE THREAD

**Issue by SoloSynth1** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#104]
Hi, thank you for all of your hard work put into making this dashboard! In general I think the UI is quite intuitive and the data and information shown is easily digestible. 

Here are a few points/feedbacks I think could make it even better:

## Larger points of feedback
> - Is the app overall well-suited to the usage scenario and target audience?
>    - Do you see some ways that the dashboard could be extended to better cater to the target audience or meet the specifications in the usage scenario?

From the `README` file, it is stated that this app "aims to empower stakeholders with insights for informed decision-making on food prices worldwide." For regional comparisons within the same country, I think the dashboard is doing a fine job. 

However, the dashboard currently does not allow users to select more than one country and thus there is no way for users to compare food prices internationally. For this, I feel adding extra charts/functionality for users to compare common food prices across countries would be very helpful in aiding the dashboard to achieve this goal in particular - that is, to visualize global food price trends for better understanding, as per the motivation and purpose stated in the proposal.

> - Was the app intuitive to use? Did it behave as you expected?
>   - This is one of the most helpful things you can comment on, since you are coming to the app with a pair of fresh eyes and without the preconception of the group that built it.

The UI is very intuitive, with all controllable components stacked inside the sidebar for easy access.

However, one un-intuitive thing in the UI I found is that no explanation is provided in the dashboard of what it is or what is the expected behaviour once the Geo-View mode is enabled.

Also the country names in the dropdown menu are not sorted lexicographically. e.g. Chad, South Africa appearing at the end of the list, which can be confusing.

Another minor issue is that the interface seems unresponsive and takes a lot of time to update when viewed on render.com. But I understand this is the constraint of deploying the dashboard within the free tier limit on that platform, which only provides a computation power of 0.1 vCPU max.

> - Can you think of other alternatives or improvements for the plots regarding the selection of the plots or how they are set up to reach to the widgets?

The Date Range widget is working fine in most cases. However, there is no quick way for users to discover the queryable date range. In other words, users will have to use the date-picker in a trial-and-error manner to find out that the available data is from 04/15/2011 and onwards. Either a small static footnote, or a pop-up shown when invalid date is selected in the date-picker would help to polish the UX in this regard.

> - Are the plots or other outputs sufficiently described / intuitive enough for the target audience?

Yes, they are; The information shown in the chart is also straightforward and does not require users to have much domain expertise to be able to make sense of it. I would assume the target audience i.e. policy makers and business owners, would be able to digest the information shown with no problem.

## Smaller points of feedback
> - Is the text on plot labels, widgets, titles, etc easy to read? Does it need to be bigger, use a different font, or be rotated differently?

They are all of appropriate sizes and fonts and are very easy to read.

> - Was the dashboard organized in a way that was easy to read (columns / rows) or you would suggest a change in this sense?
>   - Think about what we discussed during lecture 1 regarding how people read web pages.

As mentioned previously, the dashboard is already organized in a logical manner. I do not feel a change in layout is needed.

> - Would you prefer to include/remove tabs/pages?

For the current features implemented, I don't think the addition of tabs/pages would help much; But in case that the functionality for comparing food price internationally is implemented, I would prefer it to be put in another tab/page, as it does not make sense to put it together with the existing charts, which are all related to regions from within a single country.

> - Are the options that you can select in the widgets working fine or have you found some edge cases where it is not working?

- The "Enable Geo-View" button seems to be doing nothing other than hiding the charts inside the "Commodities" section.
- The "Enable Geo-View" also seems to shift out of the sidebar boundary when clicked, but this is a minor styling issue.

> - Was is easy to understand the usage scenario from reading the readme and proposal? If not, how could it be made clearer in the readme?

Yes, it was very easy to understand the usage scenario from the `README` as well as from the proposal.

Edit: typo

**Comment by JohnShiuMK** [comment]
duplicated in #106, closed
