### ISSUE TITLE
3. Addressing feedback from peers 

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#106]
## Performance issues 
 - [x] Plotting is too slow, for different countries @srfrew 
   - **Response: Implemented memoization for faster data retrieval**
 - [x] Plotting for updating commodities and markets is too slow @srfrew 
   - **Response: Implemented dynamic charting by storing commodity charts and only drawing new / changed charts**
   - The plots are not updated quickly with filter changes. It takes some time to update filters and plots. But sometimes, they get stuck and don't change at all, and they need to be changed again to make it work. #101 
   - When switching countries in the dashboard, I've noticed the plots take a while to update, possibly due to the large amount of data being processed. You might consider data sampling, such as displaying one data point per month. This can help in speeding up the plot updates without losing the overall trend information that users are interested in. #102 
   - **Widget Interaction:** I noticed some issues with the interactive widgets. Specifically, selecting different options does not update the plots accordingly, which might be frustrating for users expecting real-time data manipulation. #103 
   - **Data Loading Speed:** Transitioning between different countries or data points is somewhat slow. Optimizing data processing or considering data sampling (e.g., showing one data point per month) could improve responsiveness and user satisfaction. #103 
   - Another minor issue is that the interface seems unresponsive and takes a lot of time to update when viewed on render.com. But I understand this is the constraint of deploying the dashboard within the free tier limit on that platform, which only provides a computation power of 0.1 vCPU max.

## Docs issues
 - [x] #119
   - I could not clone the repository with the command given in the Readme. You can consider giving something like "git clone https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker.git" #101 
 - [x] #121
   - Plots are not getting displayed locally as there is package mismatch issue. Getting error RuntimeError: The versions of the vegafusion and vegafusion-python-embed packages must match and must be version 1.5.0 or greater. Found: vegafusion==1.6.6  and vegafusion-python-embed==1.6.7. However, this issue is not there on deployed dash. #101 
 - [x] #122
   - gif attached in the Readme is different from the current version. You can include gif as per latest version. #101 
 - [x] #120
   - Including a glossary or an info icon to explain technical terms like 'MoM' and 'YoY' could be beneficial for users unfamiliar with these terms.

## Layout issues
- [x] Text is clear but might benefit from a slightly larger font size to aid readability on smaller screens.
- [x] #117 @tonyshumlh 
  - Also the country names in the dropdown menu are not sorted lexicographically. e.g. Chad, South Africa appearing at the end of the list, which can be confusing.
- Non-specific
  - **Dashboard Layout:** The current layout is well-organized, yet considering the feedback from actual users on whether the rows/columns setup is optimal could provide insights into potential improvements.
  - **Label Clarity:** Ensure that all plot labels, widget titles, and other text elements are clear and easy to read.

## Potential new features
- [x] #115
  - I noticed that your proposal mentions the inclusion of a geographic view toggle. However, in the current dashboard, activating this toggle does not seem to initiate any change. Specifically, the geographical representation of data is not displayed, and only the line graph for the Food Price Index remains visible. #102 
  - **Geographic View:** The inclusion of a geographic view toggle is a great idea, yet it seems non-functional at the moment. Activating this should display different geographical data visualizations to enhance the comparative analysis between regions or countries. #103 

- [x] #131
  - The dashboard layout is intuitive. However, a brief tutorial for first-time users could improve new user experience. You might consider adding interactive elements, such as tooltips that explain what each plot represents, to make it more intuitive. #102 
  - **Intuitiveness:** The dashboard layout is intuitive; however, adding a brief tutorial could significantly enhance the user experience for newcomers. Interactive elements like tooltips would further aid in understanding the data plots. #103 

- [x] #114
  - The plots chosen are suitable for a quick glance at trends. Using a calendar to pick exact dates could be cumbersome for users who are looking for general trends rather than precise time points. I suggest implementing interactive sliders for time range selection. Sliders provide a quick and dynamic way to adjust the date range, giving users the ability to easily expand or narrow down the time period they are interested in without the need to input exact dates. #102 
  - **Time Navigation:** While the use of a calendar for selecting dates is comprehensive, it may not be the most efficient for users seeking broader trends. Implementing a slider for time range selection could provide a more dynamic and straightforward way to adjust views between specific and general timelines. #103 
  -  Using the calendar can be tricky when the start and end dates are many years apart. A more user-friendly method for adjusting dates over more extended periods, like editing manually, would be helpful. Editing in the date field does not work at this time. #102 
  - The Date Range widget is working fine in most cases. However, there is no quick way for users to discover the queryable date range. In other words, users will have to use the date-picker in a trial-and-error manner to find out that the available data is from 04/15/2011 and onwards. Either a small static footnote, or a pop-up shown when invalid date is selected in the date-picker would help to polish the UX in this regard.
  - When we select the End date to change, the calendar always opens for the start date. This creates some confusion with the data range selection.

- Out of scope
  - However, the dashboard currently does not allow users to select more than one country and thus there is no way for users to compare food prices internationally. For this, I feel adding extra charts/functionality for users to compare common food prices across countries would be very helpful in aiding the dashboard to achieve this goal in particular - that is, to visualize global food price trends for better understanding, as per the motivation and purpose stated in the proposal. #104 
  - Experimenting with different fonts or orientations could enhance visibility and user interaction.
However, one un-intuitive thing in the UI I found is that no explanation is provided in the dashboard of what it is or what is the expected behaviour once the Geo-View mode is enabled.

**Comment by celestezhao** [comment]
This error is wired... In our conda env we've set vegafusion==1.6.6 and vegafusion-python-embed==1.6.6. Where does this 1.6.7 come from?

“Plots are not getting displayed locally as there is package mismatch issue. Getting error RuntimeError: The versions of the vegafusion and vegafusion-python-embed packages must match and must be version 1.5.0 or greater. Found: vegafusion==1.6.6 and vegafusion-python-embed==1.6.7. However, this issue is not there on deployed dash.”

**Comment by JohnShiuMK** [comment]
> This error is wired... In our conda env we've set vegafusion==1.6.6 and vegafusion-python-embed==1.6.6. Where does this 1.6.7 come from?
> 
> “Plots are not getting displayed locally as there is package mismatch issue. Getting error RuntimeError: The versions of the vegafusion and vegafusion-python-embed packages must match and must be version 1.5.0 or greater. Found: vegafusion==1.6.6 and vegafusion-python-embed==1.6.7. However, this issue is not there on deployed dash.”

@celestezhao this will be resolved in #123

**Comment by JohnShiuMK** [comment]
All done, good job!
