### ISSUE TITLE
(ideas for future) UI fine-tuning

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#110]

**Comment by srfrew** [comment]
- [x] UI: Condense and move footer from chart section to sidebar. 
  - Add icon for repo instead of link. Remove text "Dashboard latest update on"
- [ ] UI: Increase height of index and commodity charts slightly
- [ ] UI: For large date ranges, remove dots from chart to minimize crowding 
- [x] UI: Glossary tooltip in sidebar for Average, MoM, YoY
- [ ] UI: Consistency. Rounded corners not consistent with UI

**Comment by srfrew** [comment]
- [ ] Implement 2 way filtering for commodities
   - Relevant Plotly example in documentation

**Comment by JohnShiuMK** [comment]
It's for future improvement, we close it for now
