### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#113]
Implement two major two minor

Major:
- [x] #115
- [x] #130

Minor:
- [x] Write about performance API call in reflection
- Should not be able to unselect country -> #130

**Comment by JohnShiuMK** [comment]
Hi @joelostblom, could you please remind us what this mean? 
> Commodities and Markets widgets should handle when there is no chart; e.g. show a message tomake selection and disable the other dropdown.

**Comment by srfrew** [comment]
My thoughts were 
- [x] Implement a short callback clearing or disabling widget selections when a new country is selected
- [x] Set existing charts to greyed out or loading states
- [x] In lieu of updating filtering to handle countries with no data, select 10 countries that are known to work for M4 MVP

**Comment by JohnShiuMK** [comment]
followed up in #105, done
