### ISSUE TITLE
Proposal: Section 1 - Motivation and Purpose

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#2]
Complete in several sentences:
Who is your target audience, and what role are you embodying?
What is the problem the target audience is facing and why is it important to solve?
How can your dashboard assist in solving this problem for the intended target audience?

**Comment by tonyshumlh** [comment]
**Introduction** 
We are a team of data scientists working within _a food-focused NGO based in Canada (e.g., Food Banks Canada, tTBC_). Our mission is to provide accessible solutions for understanding and addressing global food price trends. Our newly developed tool is designed to cater to a range of non-technical stakeholders, including policymakers, economists in the public sector, food industry business professionals and NGOs, and the general public.

**Problem Statement**
There is no denial that reliable food price information is essential for impactful decision-making across various sectors, whether it is shaping food policies to combat hunger in poor regions, or optimizing business strategies to support both profit margins and people well-being. However, we observed a lack of open, easy-to-use online platform that provide a comprehensive overview of global food price trends. Some challenges we observed include scattered and unorganized regional data that often requires technical expertise to navigate, as well as existing platforms that are not intuitive for non-technical stakeholders to utilize effectively in their daily operations. 

In response to this challenge, we propose the development of an interactive, user-friendly data visualization platform. Our platform aims to empower stakeholders to extract insights and make informed decisions regarding food prices worldwide. Key features and use cases include: 
- Regional food price level visualization, allowing policymakers to monitor and implement targeted preventive measures if needed.
- Exploration of trends in food price changes over time and geographic regions across different food categories, enabling businesses to enhance planning and resource allocation strategies.
- Accessible food price index information for the general public, facilitating financial management and awareness of cost-of-living fluctuations.

By offering our platform, we aim to enhance collaboration across sectors to address food-related challenges on a global scale.

**Comment by JohnShiuMK** [comment]
actually... I guess it may be better to edit directly in the `reports/m1_proposal.md`?
 - you can open a new branch and create a file there, or,
 - create a new branch from my `update_repo_structure` branch and edit the m1_proposal.md I created

the version history would be more transparent and easier to maintain, what do you guys think, @srfrew @tonyshumlh? :joy:

**Comment by srfrew** [comment]
I'll move this to a new branch from main now that your PR is merged to main. I'll copy it over there and draft.

**Comment by srfrew** [comment]
Branch created and edits complete; see PR: #21
