### ISSUE TITLE
Milestone 2 PRD - Technical Requirement

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#36]
Below is the technical requirement for the dashboard.

**Items**
1. Logo Design
2. Dashboard 
  - Basic
      - Graph 1 - Food Index Plot
          - Chart 1: line chart, x-axis = Date, y-axis = index, legend = Region/Market
          - Chart 2: Avg figure chart of the latest date figure over selected market , 1 or 2 Period-over-period % change (e.g. MoM, YoY)
          - Selection Toggle: Region/Market, Date, Country
              - Default value: all regions within Japan, 2011-2020, Japan
          - Questions: 
              1) how to define food index?
              2) how to normalize the food index across regions?
      - Graph 2 - Individual Commodity Plot
          - Chart 1: line chart, x-axis = Date, y-axis = index, legend = Region/Market
          - Chart 2: Avg figure chart of the latest date figure over selected market , 1 or 2 Period-over-period % change (e.g. MoM, YoY)
          - Selection Toggle: Region/Market, Date, Commodity, Country
              - Default value: all regions within Japan, full date range, Rice (?), Japan
          - Questions: 
              1) how to add multiple plots based on the number of selected commodities?
              2) how to normalize the food index across regions?
  - Geo
      - Graph - Individual Commodity Spatial Plot
          - Chart 1: geospatial chart, point = commodity & price
          - Selection Toggle: Date, Commodity (incl. food index), Country
              - Default value: latest date, Rice (?), Japan
          - Questions: 
              1) how to add multiple plots based on the number of selected commodities?
              2) how to normalize the food index across regions? 
  - Toggle
      - Display:
          - Single Selection Button/Dropdown: Basic, Geo
      - Country:
          - Single Selection Dropown: Japan, any country in the dataset
      - Date:
          - Range Filter: 2011-2020 (fixed) OR the date range in the dataset (dynamic)
          - Single Selection Button/Dropdown: 2011-2020 (fixed) OR the date range in the dataset (dynamic)
      - Commodity:
          - Multiple Selection Button/Dropdown: Rice, any item in the dataset
      - Region/Market:
          - Multiple Selection Button/Dropdown: any region in the dataset based on the SELECTED COUNTRY 

3. Test & Deployment
- TBC

**Comment by JohnShiuMK** [comment]
it's addressed, thanks
