### ISSUE TITLE
3. Deployment on render

### ISSUE THREAD

**Issue by srfrew** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#38]
Deployment: 
- [x] deploy to https://render.com
- [x] link GitHub repo
- [x] disable automatic deployment and manually deploy M2 release
- [x] Enable and show at least 3 PR deploy previews
- [x] Include version numbers in `requirements.txt`. 
- [x] Include `gunicorn` package
- [x] Update "about" section of repository
    - [x] one sentence description of project in "Description" field
    - [x] include link to deployed dashboard in "Website" field 
    - [x] Include 3-5 keywords in "Topics" field (related to dashboard components / visualizations used)
- [x] #55

**Comment by JohnShiuMK** [comment]
Enable and show at least 3 PR deploy previews:
  - 1st PR deploy preview #44

**Comment by JohnShiuMK** [comment]
reference: https://pages.github.ubc.ca/mds-2023-24/DSCI_532_viz-2_students/lectures/3-charts_layouts_deployment.html#deployment

**Comment by JohnShiuMK** [comment]
Enable and show at least 3 PR deploy previews:

2nd PR deploy preview #47 
3rd PR deploy preview #49
