### ISSUE TITLE
Proposal: Section 3 - Research questions and usage scenarios

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#4]
The purpose of this section is to get you to think in more detail about how your target audience will use the app you're designing and to account for these detailed needs in the proposal.
- For this it can be helpful to create a [brief persona description](https://engineering-shiny.org/dont-rush-into-coding.html#building-personas) of a member in your intended target audience
- Then, think about what they might want to do with your app and write small user story. User stories are typically written in a narrative style and include:
  - The specific context/background of the user
  - The overall goal of the user
  - Tasks needed to reach that goal
  - A hypothetical walkthrough of how the user would accomplish those tasks with your app
  - The outcome/action that the user would take based on the information they find in the app

**Comment by tonyshumlh** [comment]
We would divide the research questions and scenarios based on various sectors below.

**Public Sector**
Ms. Tiffany is an executive with the Ministry of Health, Labour and Welfare in Japan. Her role involves policy-making related to food supply, demand, and price dynamics. Her primary goal is to ensure that food prices across regions and major categories remain at acceptable levels to safeguard public well-being. In response to any identified issues based on the data, she has to frame policy or recommend immediate measures for the government.

1. When Ms. Tiffany accesses our platform and lands on the dashboard, she immediately sees the overview of current food price index and the price levels of major food categories displayed.
2. She notices that the price of rice is close to the government-prescribed threshold and decides to investigate further.
3. Ms. Tiffany selects the rice category and adjusts the time period to view recent 2-year price trends. She identifies a slight upward trend in rice prices over the past month that arouses her concern.
4. To understand if this trend is global or local, she views the geospatial chart provided illustrating rice price distributions across regions. She observes that prices in Kansai region are significantly higher than the national average.
5. Ms. Tiffany shares her findings and views with stakeholders and proposes policy measures to regulate rice prices in the affected region. She also initiates discussions with the government regarding potential emergency aid operations to address any immediate food demand concerns.
6. She safeguards public well-being in the affected region through the use of our platform.

**Private Sector**
Mr. Joel operates a business specializing in the supply and trade of cereals and tubers. He needs to analyze market trends and price data for these commodities to identify mismatches in supply and demand, aiming to optimize profit margins. He wants to use food price data analysis to detect profitable opportunities and adjust his business operations to increase returns.

1. Mr. Joel logs into the data platform and sets up his dashboard to display trend charts for his key commodities like wheat, potatoes, and rice.
2. He examines the price trends over selected time frames to spot any significant uptrend or downtrend, and determines the profitable commodities his business should focus on. 
3. Mr. Joel adjusts the time frame of the charts to identify seasonal patterns of the prices of commodities, and notices a seasonal upward trend for potato price. in the coming months. He decides to import more potato and allocates more space in his warehouse for the stock. 
4. Mr. Joel then explores the geospatial charts, which show the regional price distribution for his main products, identifying areas with higher price levels that indicate a demand surplus.
5. Based on the findings, he considers reallocating his stock to regions where he can sell at higher prices and plans his logistics to align with these insights.
6. He achieves a higher return on his food business and solves demand mismatch through the use of our platform.

**General Public**
TBC if needed

**Comment by srfrew** [comment]
Thank you Tony! I'll copy over to the proposal and take it from here

**Comment by srfrew** [comment]
Branch created and edits complete; see PR: #21
