### ISSUE TITLE
4. box function

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#40]

**Comment by tonyshumlh** [comment]
Description:
- Build the Box Figure Chart generator function as illustrated
<img width="272" alt="Screenshot 2024-04-03 at 5 52 23 PM" src="https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker/assets/38127942/84cefa4d-9c57-49a9-999f-7269513fa901">
