### ISSUE TITLE
Proposal: Section 4 - App sketch & brief description

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#5]
Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

Complement the sketch with a high level description of the main components in the app interface and how the user will interact with it. You are not required to use terminology specific to Dash/Shiny (i.e. widgets, components, etc...).

Remember to be realistic about your expectations and plans since you will actually be implementing this app (but again, you will not be penalized if you need to adjust a bit in later milestones). It is better to design a slightly more limited app that you have time to implement well, instead of a complicated app that you don't have time to finish. At the same time, you cannot just make a single bar chart and call it a day; the app needs to have several input and output panels. You can view the dashboards from previous years students in the [DSCI 532 showcase](https://five32-dashboard-showcase.onrender.com/) (might take several seconds to load) as a complexity target and to get inspiration for your final app. Your TA will be able to help you with this as well, and provide feedback on whether your app is too simple or too complex.

**Comment by JohnShiuMK** [comment]
Note for calculating geometric mean in index:

At the most detailed level, the elementary aggregate level (for example, men's shirts sold in department stores in San Francisco), detailed weighting information is unavailable, so indices are computed using an unweighted [arithmetic](https://en.wikipedia.org/wiki/Arithmetic_mean) or [geometric mean](https://en.wikipedia.org/wiki/Geometric_mean) of the prices of the sampled products. (However, the growing use of [barcode scanner](https://en.wikipedia.org/wiki/Barcode_reader) [data](https://en.wikipedia.org/wiki/Data) is gradually making weighting information available even at the most detailed level.)

Reference: https://en.wikipedia.org/wiki/Consumer_price_index#Overview

**Comment by tonyshumlh** [comment]
![Group19_basic](https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker/assets/38127942/dc0ff5a1-a8e7-49a5-a9ec-1b74175b024a)
![Group19_advgeo](https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker/assets/38127942/c1071bc5-7ee8-4627-a2dc-0c50f64b41ba)
@JohnShiuMK

**Comment by JohnShiuMK** [comment]
done, merged into #15
