### ISSUE TITLE
(milestone 2) add the footer in the dashboard: description, authors, link to the repo, last update date

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#51]
- a short description of the app, who has made it, a link to the repo, and the date of the latest update/deployment.
- Example: https://five32-dashboard-showcase.onrender.com/

**Comment by tonyshumlh** [comment]
Draft
```
Food Price Tracker is developed by Celeste Zhao, John Shiu, Simon Frew, Tony Shum. 
The application provides global food price visualization to enhance cross-sector collaboration on worldwide food-related challenges.
[Link to the Github Repo](https://github.com/UBC-MDS/DSCI-532_2024_19_food-price-tracker)
Latest update on {date, should be able to do it with code}
```

**Comment by celestezhao** [comment]
I would suggest to add an intro to the data source as well:

The raw data is from Global Food Prices dataset, openly available via [The Humanitarian Data Exchange (HDX)](https://data.humdata.org/dataset/global-wfp-food-prices). This dataset originates from the World Food Programme Price Database and includes pricing for items such as maize, rice, beans, fish, and sugar. This data spans 98 countries and approximately 3,000 markets, beginning as early as 1992 for certain countries. The data is reported in monthly intervals.
