### ISSUE TITLE
Update the "About" section in Github repo

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#52]
- Include a one-sentence description of your project in the "Description" field.
- Include the link to your deployed dashboard in the "Website" field.
- Include ~3-5 keywords in the "Topics" field. For this project, these keywords should be related to the dashboard components and visualizations you are including, e.g. "slider", "dropdown", "map", etc.

**Comment by tonyshumlh** [comment]
Done

**Comment by JohnShiuMK** [comment]
thanks @tonyshumlh
