### ISSUE TITLE
Include hierarchy of date in date widget to include both yyyy and yyyy-mm

### ISSUE THREAD

**Issue by tonyshumlh** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#64]

**Comment by srfrew** [comment]
I've looked through the documentation on this one and there doesn't seem to be many good solutions. Other than leaving it as is, we could make manual dropdowns for months and years, which would complicate callbacks significantly. 

I would recommend leaving it as is and encouraging the user to just type in the years of interest.
