### ISSUE TITLE
Teamwork contract

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#7]
link / updates to be included

**Comment by celestezhao** [comment]
Hi team, please find a draft of our work contract in below Google doc link:
https://docs.google.com/document/d/1r-KiBMEenw_1QyjyEH00ksCeMapthjajOQ4u3NczZ5M/edit?usp=sharing

After we have finished this, we can convert it into .md file for submission.

**Comment by JohnShiuMK** [comment]
@srfrew to save into teamwork-contract.md and submit
