### ISSUE TITLE
7. Get inspiration from your peers (Challenging)

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#73]
rubric={viz:5}

I have created [a meta-dashboard for all your dashboards from milestone 2](https://five32-dashboard-showcase-2024.onrender.com/). My main intent with this is to make it easier for you to see what other groups are working on, and get inspiration for your own dashboard. For the challenging section of this milestone, you should find one aspect from another group that you also implement in your own dashboard, or use for inspiration to implement something similar. This could either be from the group one of you have reviewed or from another group whose dashboard you found inspiring.

For example, this could be that you saw how another group had hooked up the callbacks between widgets in a clever manner, that they are using a certain type of chart that you realize is more suitable for your data than the one you are currently using, or that they way they designed some aspect of their layout would work well in your dashboard too. It is not enough if it is a very minor things such as you like the color they used for their buttons, and picked the same color for yours (but if there are many small things, that could be fine). If you are unsure, you can reach out to me. To be clear, this is not about copying another groups work verbatim, but to get inspiration for how you can incorporate similar functionality or design after adapting it to the context of your own dashboard.

If you attempt the challenging question, you should write about what you did in the reflection document so that it is clear what to assess when grading. Include which group's dashboard you used for inspiration and why you think this approach is beneficial for your dashboard.

**Comment by celestezhao** [comment]
- [x] Aesthetics of the dashboard
- [x] Break the coding files into really small pieces

**Comment by srfrew** [comment]
I think the geo-code implementation can be simultaneously challenging and a peer-feedback component. #84

**Comment by srfrew** [comment]
To expand the aesthetics of the dashboard idea, here were some of my thoughts 
- [x] decrease the width of the top title bar, it takes up quite a bit of screen real estate imo
- [ ] double check the column / rows in the top title bar, if it is in a half-page view the title overflows for some reason
- [ ] set the sidebar width to be a proportion of the screen instead of a fixed width with max and min amounts, allows for scaling 
- [ ] decrease the sidebar width overall, as it is taking up a bit too much space imo, maybe closer to 20%? 
- [ ] embed the legend of the chart in the chart itself and not outside it to maximize chart area (altair may be able to do this automatically to avoid clipping data)

**Comment by celestezhao** [comment]
> To expand the aesthetics of the dashboard idea, here were some of my thoughts
> 
> * [x]  decrease the width of the top title bar, it takes up quite a bit of screen real estate imo
> * [ ]  double check the column / rows in the top title bar, if it is in a half-page view the title overflows for some reason
> * [ ]  set the sidebar width to be a proportion of the screen instead of a fixed width with max and min amounts, allows for scaling
> * [ ]  decrease the sidebar width overall, as it is taking up a bit too much space imo, maybe closer to 20%?
> * [ ]  embed the legend of the chart in the chart itself and not outside it to maximize chart area (altair may be able to do this automatically to avoid clipping data)

For the sidebar width, it is set fixed as this can keep date selection and dropdown widgets have same width...there might be some other ways, let's address it in Milestone 4.
