### ISSUE TITLE
5. Break code into multiple files

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#75]
rubric={accuracy:15}

As your code base grows, it is now a good idea to break it into multiple files, instead of having a giant app.py file. You have already covered modularization earlier in the program, and we will talk about it in class this week in the context of dashboards (including how to make it work locally and on the deployed server), but generally you can put data preprocessing relating functions in one file, layout-related functions in another file, and split the server side into as many files as makes sense to you based on your apps functionality.

**Comment by JohnShiuMK** [comment]
Employ "Single-page app with multiple files" in lecture 6

**Comment by srfrew** [comment]
@JohnShiuMK , this is ready for a PR, I'll double check and ping you shortly.
