### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#77]
- [x] #78
- [x] #80
- [x] Performance issues (don't have to deal with now)
- [x] #93

Minor:
- [x] #95
- [x] #79

**Comment by JohnShiuMK** [comment]
performance issues --> milestone 4

 - [x] make the breakdown charts are smaller, e.g. two items per row
 - [x] update between dropdown to filter, so that the chart exists
 - [x] turn off the "...", see lecture 5 note
 - [ ] (optional) table, for inputing numbers
 - [x] polish title
