### ISSUE TITLE
Meeting minutes on 2024-03-25 & Agenda for 2024-03-27

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#8]
for details: https://docs.google.com/document/d/14-Rh6YbjKVDXQTv49jrvbf8x7jUAjajzUuS8AHxf2s0/edit

Action items:
 - [x] Github repo (by John)
 - [x] Work contract (by Indiv)
 - Proposal
    - [x] Motivation and Purpose - Tony / Simon
    - [x] Data descriptor - Celeste
    - [x] Research questions and usage scenarios - Tony / Simon
    - [x] App sketch and brief description - John

**Comment by JohnShiuMK** [comment]
to be closed when we finish the contract and proposal

**Comment by JohnShiuMK** [comment]
## Meeting Agenda for 2024-03-27:
 - review agenda (3 mins)
 - walk through the teamwork contract together and electrically sign (5 mins)
 - decide who to submit the milestone 1 (he/she will keep the work contract for submission) (3 mins)
 - review the proposal section 1 - 3 (Tony and Simon to briefly present?) (5 mins)
 - discuss and update the design sketch (30 mins)
 - segregate works: (5 mins) 
   - (if necessary) fine-tuning proposal section 
   - finalizing proposal (reports/m1_proposal.md)
   - updating README (project title and summary of proposal)
   - EDA / Challenging part 

@srfrew @tonyshumlh @celestezhao 
Looking forward to seeing you guys tmr. I have drafted an agenda here to facilitate our discussion tmr. The times are roughly estimated, but I guess we will more or less need an hour.

What do you think?

**Comment by srfrew** [comment]
Looks great! Well on track to complete on my end. Thank you for putting this together!

**Comment by JohnShiuMK** [comment]
- Simon to save into teamwork-contract.md: https://docs.google.com/document/d/1r-KiBMEenw_1QyjyEH00ksCeMapthjajOQ4u3NczZ5M/edit
- Simon to submit the milestone 1
- Simon to shorten the user stories by using some bullet points (John to share the research questions in bullet points for each user)
- Tony to suggest change of the statement in the section 2

**Comment by JohnShiuMK** [comment]
great discussion, will close this now
