### ISSUE TITLE
(milestone 4) Revise the Score Card chart

### ISSUE THREAD

**Issue by JohnShiuMK** [UBC-MDS/DSCI-532_2024_19_food-price-tracker#83]

**Comment by srfrew** [comment]
The score card chart may be implicated in performance issues documented in #61 and worked on in #87 

I'll see how far it goes.

**Comment by srfrew** [comment]
Seems as tho @celestezhao's UI changes may have impacted this Issue!

**Comment by JohnShiuMK** [comment]
I think this can be considered as solved.
Let's discuss on Monday

**Comment by JohnShiuMK** [comment]
confirmed this is resolved already, close
